// packages/react_default/src/App.tsx
import { LicenseKeyboard } from './packages';
import * as React from 'react';
import './App.css';

import { useState } from 'react';

function App() {
  const [showKeyboard, setShowKeyboard] = useState(false);
  const [value, setValue] = useState('');
  const [rule, setRule] = useState('');

  return (
    <div>
      <button
        data-test-id="controlButton"
        onClick={() => setShowKeyboard(!showKeyboard)}
        type="submit"
      >{`${showKeyboard ? 'close' : 'open'} the keyboard`}</button>

      <p data-test-id="value">{value}</p>
      <LicenseKeyboard
        visible={showKeyboard}
        showNum={false}
        done={() => setShowKeyboard(false)}
        onChange={(value: any) => setValue(value)}
        onCurRule={(r)=>{
          if(r !== rule && showKeyboard){
            setRule(r);
          }
          console.log('222222', r);
        }}
        value={value}
        defalutConfig={
          {
            // "使": [
            //   ['ZCDEFGHJKLMNOPQRS', 'ABCDEFGHJK', '0123456789', '0123456789', '0123456789', '0123456789', '0123456789']
            // ],
            // "京": [
            //   ['ABC', 'ABC', 'ABC', 'ABC', 'ABC', 'ABC', 'ABC'],
            //   ['ZCDEFGHJKLMNOPQRS', 'ABCDEFGHJK', '0123456789', '0123456789', '0123456789', '0123456789', '0123456789']
            // ]
          }
        }
      />
    </div>
  );
}

export default React.memo(App);

// packages/vue_default/src/App.vue
<template>
  <div>
    <button
      data-test-id="controlButton"
      @click="toggleKeyboard"
      type="submit"
    >
      {{ showKeyboard ? 'close' : 'open' }} the keyboard
    </button>

    <p data-test-id="value">{{ value }}</p>
    <LicenseKeyboard
      v-if="showKeyboard"
      :visible="showKeyboard"
      @done="hideKeyboard"
      @onChange="updateValue"
      @onCurRule="handleonCurRule"
      :value="value"
    />
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
// const confirmButtonText = "确定"
// const cellTextStyle = {
//   color: 'red',
//   fontSize: '16px'
// }
// const cellDivStyle = {
//   backgroundColor: 'black',
// }
const showKeyboard = ref(false);
const value = ref('');

const toggleKeyboard = () => {
  showKeyboard.value = !showKeyboard.value;
};

const hideKeyboard = () => {
  showKeyboard.value = false;
};

const updateValue = (newValue:string) => {
  value.value = newValue;
};
const handleonCurRule = (text: string) => {
  console.log('text', text);
}
</script>

<style scoped>
/* Add your CSS styles here */
</style>
