// packages/react_default/src/packages/LicenseKeyboard/index.tsx
import * as React from 'react';
import { createPortal } from 'react-dom';
import {
  firstScreen,
  localConfig,
  secondScreen,
} from '../config/index';
import './Index.css';
import KeyCell from './cell';
import { KeyboardProps } from './interface';

enum secondScreenStatus {
  DisableAll = 0,
  AllowAll,
  AlphabetOnly,
  NumberOnly,
  NoNumberOnly,
  AllowSpecialCharaters,
}
interface JudgeRulesArgs {
  key: string;
  len: number;
  currentValue: string | undefined; // 根据需要调整类型
}
interface DefaultConfig {
  [key: string]: string[];
}
type secondScreenType = secondScreenStatus | string;
const requestAnimationFrame = window.requestAnimationFrame;

const document = window.document;

const easeOut = (progress: number) => {
  let v = progress;
  return Math.pow(--v, 5) + 1;
};

// 字母
const isAlphabet = (s: string) => /[ABCDEFGHJKLMNPQRSTUVWXYZ]/.test(s);
//数字
const isNumber = (s: string) => /[0-9]/.test(s);
// 特殊字符
const isSpecialCharacters = (s: string) => /[港澳学警领挂使]/.test(s);

// 判断输入
const judgeInput = (s: string, onlyAllows: secondScreenType): boolean => {
  if (typeof onlyAllows === 'string') {
    return onlyAllows.indexOf(s) !== -1;
  } else if (onlyAllows === secondScreenStatus.AllowAll) {
    return isAlphabet(s) || isNumber(s);
  } else if (onlyAllows === secondScreenStatus.AlphabetOnly) {
    return isAlphabet(s);
  } else if (onlyAllows === secondScreenStatus.NumberOnly) {
    return isNumber(s);
  } else if (onlyAllows === secondScreenStatus.AllowSpecialCharaters) {
    return isAlphabet(s) || isNumber(s) || isSpecialCharacters(s);
  } else if (onlyAllows === secondScreenStatus.NoNumberOnly) {
    return !isNumber(s);
  } else {
    return false;
  }
};

const LicenseKeyboard = React.memo((props: KeyboardProps) => {
  const [defaultConfig, setDefaultConfig] = React.useState({});
  const [state, setState] = React.useState({
    keyboardOffsetProgress: 0,
  });
  const node = React.useRef<Element | null>(null);

  let elapsed = 0;
  let startTime = 0;
  let totalTime = 0;

  const resetTime = () => {
    startTime = performance.now();
    totalTime = 300;
  };
  const handleTouchStart = () => {};

  const handleTouchMove = (event: Event) => {
    event.preventDefault();
  };
  const creat = () => {
    node.current =
      document.querySelector('#auto-vehicle-plate-key-board') ||
      document.createElement('div');
    node.current.id = 'auto-vehicle-plate-key-board';
    document.body.appendChild(node.current);
    node.current.addEventListener('touchstart', handleTouchStart);
    node.current.addEventListener('touchmove', handleTouchMove);
  };

  const remove = () => {
    const currentNode = node.current;
    if (currentNode) {
      currentNode.removeEventListener('touchstart', handleTouchStart);
      currentNode.removeEventListener('touchmove', handleTouchMove);
    }
  };
  const animationTick = (now: number, direction: 'UP' | 'DOWN' = 'UP') => {
    elapsed = now - startTime;
    const progress = Math.min(easeOut(elapsed / totalTime), 1);

    setState((prevState) => ({
      ...prevState,
      keyboardOffsetProgress: direction === 'UP' ? progress : 1 - progress,
    }));

    if (progress < 1) {
      requestAnimationFrame((time: number) => animationTick(time, direction));
    }
  };
  const show = () => {
    creat();
    setDefaultConfig(localConfig(props?.defalutConfig || {}));
    resetTime();
    requestAnimationFrame(animationTick);
  };

  const hide = () => {
    resetTime();
    requestAnimationFrame((time) => animationTick(time, 'DOWN'));
  };

  const handleDone = () => {
    props.done();
  };

  const handleEnter = (cell: string) => {
    if (props.value.length < 8 && props.onChange) {
      props.onChange(props.value + cell);
    }
  };

  const handleDelete = () => {
    if (props.value.length > 0 && props.onChange) {
      props.onChange(props.value.slice(0, -1));
    }
  };
  const renderBackBtn = () => (
    <section
      className={`${'back-btn'} ${
        props.value.length === 0 ? 'cell-disabled' : 'cell-no-disabled'
      }`}
      onClick={handleDelete}
      key={'backBtn'}
    >
      <div className="back-btn-box">
        <span className="back-btn-svg">&#9003;</span>
      </div>
    </section>
  );
  const renderDoneBtn = () => (
    <section
      className={`${'back-btn '} ${
        props.value.length === 0 ? 'cell-disabled' : 'cell-no-disabled'
      }`}
      onClick={handleDone}
      key={'backBtnDone'}
    >
      <div className="back-btn-box back-btn-done">
        <span className="back-btn-label">完成</span>
      </div>
    </section>
  );
  const renderProvinceSelect = () => (
    <article className="keyboard-container">
      {firstScreen?.map((row, index: number) => {
        return (
          <section className="keyboard-row keyboard-row-province" key={'firsts' + `${index}`}>
          {row.map((province: string) => (
            <KeyCell
              cellTextStyle={props.cellTextStyle}
              cellDivStyle={props.cellDivStyle}
              cell={province}
              key={province}
              onClick={handleEnter}
              type="province"
            />
          ))}
        </section>
        )
        }
      )}
    </article>
  );
  const renderNumberABCSelect = (
    type: secondScreenType = secondScreenStatus.DisableAll,
  ) => (
    <article className="keyboard-container keyboard-container-noprovince">
      <section className="keyboard-row">
        {secondScreen[0].map((cell: string) => (
          <KeyCell
            cellTextStyle={props.cellTextStyle}
            cellDivStyle={props.cellDivStyle}
            cell={cell}
            key={cell}
            onClick={handleEnter}
            disabled={!judgeInput(cell, type)}
            type="normal"
          />
        ))}
      </section>
      <section className="keyboard-row">
        {secondScreen[1].map((cell: string) => (
          <KeyCell
            cellTextStyle={props.cellTextStyle}
            cellDivStyle={props.cellDivStyle}
            cell={cell}
            key={cell}
            onClick={handleEnter}
            disabled={!judgeInput(cell, type)}
            type="normal"
          />
        ))}
      </section>
      <section className="keyboard-row">
        {secondScreen[2].map((cell: string) => (
          <KeyCell
            cellTextStyle={props.cellTextStyle}
            cellDivStyle={props.cellDivStyle}
            cell={cell}
            key={cell}
            onClick={handleEnter}
            disabled={!judgeInput(cell, type)}
            type="normal"
          />
        ))}
      </section>
      <section className="keyboard-row">
        {secondScreen[3]
          .map((cell: string) => (
            <KeyCell
              cellTextStyle={props.cellTextStyle}
              cellDivStyle={props.cellDivStyle}
              cell={cell}
              key={cell}
              onClick={handleEnter}
              disabled={!judgeInput(cell, type)}
              type="normal"
            />
          ))
          .concat(renderBackBtn()).concat(renderDoneBtn())}
      </section>
    </article>
  );
  React.useEffect(() => {
    if (props.visible) {
      show();
    } else {
      hide();
    }
    return () => {
      remove();
    };
  }, [props.visible]);
  const mergeAndRemoveDuplicates = (stringsArray: any[]) => {
    // 创建一个空的 Set 来存储字符串
    const mergedSet = new Set();
    // 遍历传入的字符串数组
    stringsArray.forEach((str) => {
      if (str) {
        // 将字符串按空格分割成单词，并添加到 Set 中
        str.split('').forEach((word: string) => mergedSet.add(word));
      }
    });
    // 将 Set 转换回数组并用空格连接成一个字符串
    return Array.from(mergedSet).join('');
  };
  const judgeRules = ({ key, len, currentValue }: JudgeRulesArgs): string => {
    const provinceArr = (defaultConfig as DefaultConfig)[key] || [];
    const arr: string[] = [];
    const newArr: string[] = [];
    provinceArr?.forEach((item) => {
      arr.push(item[len]);
      if (len > 0) {
        let flag = false;
        currentValue
          ?.slice(1)
          ?.split('')
          ?.forEach((ites, ind) => {
            if (item[ind] && item[ind].indexOf(ites) === -1) {
              flag = true;
            }
          });
        if (!flag) {
          newArr.push(item[len]);
        }
      }
    });
    const rules = mergeAndRemoveDuplicates(newArr?.length > 0 ? newArr : arr);
    return rules;
  };
  const renderKeyboard = () => {
    const vArr = props?.value.split('');
    const len = props.value.length;
    let rule = '';
    if (vArr?.length > 0) {
      // 计算规则
      rule = judgeRules({
        key: vArr[0],
        len: len - 1,
        currentValue: props.value,
      });
      if (props.onCurRule && props.visible) {
        props.onCurRule(rule);
      }
    }
    switch (len) {
      case 0:
        return renderProvinceSelect();
      case 1:
      case 2:
      case 3:
      case 4:
      case 5:
      case 6:
      case 7:
        if (!rule) {
          return renderNumberABCSelect(secondScreenStatus.DisableAll);
        }
        return renderNumberABCSelect(rule);
      default:
        return renderNumberABCSelect(secondScreenStatus.DisableAll);
    }
  };

  if (node.current) {
    return createPortal(
      <section
        style={{
          transform: `translateY(calc(${
            1 - state.keyboardOffsetProgress
          } * 100%))`,
        }}
        className="vehicle-plate-keyboard-container"
      >
        <section className="confirm">
            请输入车牌号
          <div className="delWrapper" onClick={handleDone}>
            <div
              style={props.confirmButtonStyle}
              className="close"
            >
            </div>
          </div>
        </section>
        <section className="keyboard">{renderKeyboard()}</section>
      </section>,
      node.current,
    );
  }

  return null;
});

export default LicenseKeyboard;

// packages/vue_default/src/packages/licenseKeyboard/licenseKeyboard.vue
<template>
  <div 
    id="auto-vehicle-plate-key-board"
    v-if="visible"
    >
    <section
      class="vehicle-plate-keyboard-container"
    >
      <section className="confirm">
            请输入车牌号
          <div className="delWrapper"  @click="handleDone">
            <div
              style={props.confirmButtonStyle}
              className="close"
            >
            </div>
          </div>
        </section>
      <section class="keyboard">
        <RenderProvinceSelect
          v-if="value.length === 0 && charType === '数字'"
          :value="value"
          :firstScreen="firstScreen"
          :secondScreen="secondScreen"
          :cellTextStyle="cellTextStyle"
          :cellDivStyle="cellDivStyle"
          @handleEnter="handleEnter"
          @handleDelete="handleDelete"
        />
        <RenderNumberSelect
          v-else-if="charType === '中文'"
          :firstNumberScreen="firstNumberScreen"
          :value="value"
          :type="onlyAllows"
          :cellTextStyle="cellTextStyle"
          :cellDivStyle="cellDivStyle"
          @handleEnter="handleEnter"
          @handleDelete="handleDelete"
        />
        <renderNumberABCSelect
          v-else
          :secondScreen="secondScreen"
          :value="value"
          :type="onlyAllows"
          :cellTextStyle="cellTextStyle"
          :cellDivStyle="cellDivStyle"
          @handleEnter="handleEnter"
          @handleDelete="handleDelete"
          @handleDone="handleDone"
        />
      </section>
    </section>
  </div>
  </template>
  
  <script setup lang="ts">
  import { ref, onMounted, onUnmounted, defineProps, watch, StyleValue } from 'vue';
  import { localConfig, ObjType, provinceSelect, numberSelect, numberAbcSelect,secondScreenStatus  } from './config'
  import { mergeAndRemoveDuplicates } from './utils'
  interface DefaultConfig {
    [key: string]: string[];
  }
  const props = defineProps<{
    value: string;
    visible: boolean;
    defalutConfig?: ObjType;
    confirmButtonText?: string;
    confirmButtonStyle?: StyleValue;
    cellTextStyle?: StyleValue;
    cellDivStyle?: StyleValue;
  }>();
  const emit = defineEmits([ "onChange", "done", 'onCurRule']);
  const charType = ref('数字');
  const firstScreen = ref<string[][]>(provinceSelect);
  const secondScreen = ref<string[][]>(numberAbcSelect);
  const firstNumberScreen =  ref<string[][]>(numberSelect);
  const defaultConfig = localConfig(props?.defalutConfig || {});
  const onlyAllows = ref(secondScreenStatus.AllowAll || '');

  const judgeRules = ({ key, len, currentValue }: any): string => {
    const provinceArr = (defaultConfig as DefaultConfig)[key] || [];
    const arr: string[] = [];
    const newArr: string[] = [];
    provinceArr?.forEach((item) => {
      arr.push(item[len]);
      if (len > 0) {
        let flag = false;
        currentValue
          ?.slice(1)
          ?.split('')
          ?.forEach((ites:string, ind:number) => {
            if (item[ind] && item[ind].indexOf(ites) === -1) {
              flag = true;
            }
          });
        if (!flag) {
          newArr.push(item[len]);
        }
      }
    });
    const rules = mergeAndRemoveDuplicates(newArr?.length > 0 ? newArr : arr);
    return rules;
  };
  const handleOnCurRule = (rule: string) => {
    emit('onCurRule', rule);
  };
  watch(()=>props.value,(newValue)=>{
    const vArr = newValue.split('');
    const len = newValue.length;
    if (charType.value === '中文'){
      onlyAllows.value = secondScreenStatus.NumberOnly;
      if (props.visible) {
        let n = '0123456789';
        if (len == 7){
          n = '';
        }
        handleOnCurRule(n);
      }
      if (newValue?.length === 7){
        onlyAllows.value = secondScreenStatus?.DisableAll;
      }
      if (newValue?.length === 6){
        onlyAllows.value = secondScreenStatus?.NoNumberOnly;
      }
    }else{
      let rule = '';
      if (vArr?.length > 0) {
        // 计算规则
        rule = judgeRules({
          key: vArr[0],
          len: len - 1,
          currentValue: newValue,
        });
      }
      handleOnCurRule(rule);
      onlyAllows.value = rule;
    }
  },{immediate:true,deep:true})
  const handleDone = () => {
    emit('done');
  };
  
  const handleEnter = (cell: string) => {
    if (props.value.length < 8) {
      emit('onChange', props.value + cell);
    }
  };
  
  const handleDelete = () => {
    if (props.value.length > 0) {
      emit('onChange', props.value.slice(0, -1));
    }
  };
  onMounted(() => {
    // Show keyboard logic
  });
  
  onUnmounted(() => {
    // Hide keyboard logic
  });
  
  </script>
  <script lang="ts">
    import { defineComponent } from 'vue';
    import KeyCell from './KeyCell.vue';
    import RenderProvinceSelect from './renderProvinceSelect.vue';
    import RenderNumberSelect from './renderNumberSelect.vue';
    import RenderNumberABCSelect from './renderNumberABCSelect.vue';
    
    export default defineComponent({
      name: 'LicenseKeyboard',
      components: {
        KeyCell,
        RenderProvinceSelect,
        RenderNumberSelect,
        RenderNumberABCSelect,
      },
      // 组件的其余逻辑...
    });
  </script>
  <style>
#auto-vehicle-plate-key-board .vehicle-plate-keyboard-container {
  position: fixed;
  min-height: 250px;
  background-color: #e8e9eb;
  bottom: 0;
  padding-bottom: constant(safe-area-inset-bottom);

  /* 兼容 iOS < 11.2 */
  padding-bottom: env(safe-area-inset-bottom);

  /* 兼容 iOS >= 11.2 */
  left: 0;
  right: 0;
  box-shadow: 0 0 6px 0 rgba(0, 0, 0, 20%);
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial,
    sans-serif;
}
@supports not (constant(safe-area-inset-top)) {
  #auto-vehicle-plate-key-board .vehicle-plate-keyboard-container {
    padding-bottom: 15px;
  }
}
#auto-vehicle-plate-key-board .vehicle-plate-keyboard-container * {
  user-select: none;
  -webkit-tap-highlight-color: transparent;
  outline: none;
}

#auto-vehicle-plate-key-board
  .vehicle-plate-keyboard-container
  *:not(input, textarea) {
  -webkit-touch-callout: none;
  user-select: none;
}

#auto-vehicle-plate-key-board .vehicle-plate-keyboard-container .confirm {
  width: 100%;
  height: 44px;
  display: flex;
  justify-content: center;
  align-items: center;
  background-color: rgba(255,255,255,.9);
  position: relative;
}

#auto-vehicle-plate-key-board .vehicle-plate-keyboard-container .confirm .btn {
  font-size: 14px;
  color: #08f;
  text-align: right;
  margin-right: 10px;
  margin-top: 5px;
}
.delWrapper{
  width: 44px;
  height: 44px;
  position: absolute;
  right: 0px;
  top: 0px;
  z-index: 9999;
}
.close {
  position: relative;
}

.close::before,
.close::after {
  position: absolute;
  content: ' ';
  background-color: #111;
  top: 12px;
  left: 20px;
  width: 1.5px;
  height: 20px;
}

.close::before {
  transform: rotate(45deg);
}

.close::after {
  transform: rotate(-45deg);
}
#auto-vehicle-plate-key-board
  .vehicle-plate-keyboard-container
  .confirm
  .back-abc {
  font-size: 14px;
  display: flex;
  justify-content: center;
  align-items: center;
  margin-top: 5px;
  margin-left: 10px;
}

#auto-vehicle-plate-key-board .vehicle-plate-keyboard-container .keyboard {
  background-color: #e8e9eb;
  display: flex;
  justify-content: center;
  align-items: center;
}

#auto-vehicle-plate-key-board
  .vehicle-plate-keyboard-container
  .keyboard
  .keyboard-container {
  display: flex;
  flex-direction: column;
  width: 100%;
  align-items: center;
}

#auto-vehicle-plate-key-board
  .vehicle-plate-keyboard-container
  .keyboard
  .keyboard-container.keyboard-container-province {
  height: 223px;
}

#auto-vehicle-plate-key-board
  .vehicle-plate-keyboard-container
  .keyboard
  .keyboard-container
  .back-btn {
  flex: 2;
  height: 44px;
  display: flex;
  justify-content: center;
  align-items: center;
}
#auto-vehicle-plate-key-board
  .vehicle-plate-keyboard-container
  .keyboard
  .keyboard-container
  .back-btn
  .back-btn-box{
  width: 100%;
  height: 100%;
  margin: 4px 2.5px;
  background-color: white;
  border-radius: 4px;
  display: flex;
  justify-content: center;
  align-items: center;
}
#auto-vehicle-plate-key-board
  .vehicle-plate-keyboard-container
  .keyboard
  .keyboard-container
  .back-btn
.back-btn-done{
  background-color: #206cfe;
}
#auto-vehicle-plate-key-board
  .vehicle-plate-keyboard-container
  .keyboard
  .keyboard-container
  .keyboard-row {
    width: 100%;
  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;
}


#auto-vehicle-plate-key-board
  .vehicle-plate-keyboard-container
  .keyboard
  .keyboard-container
  .keyboard-row-province {
    width: 100%;
  display: flex;
  flex-direction: row;
  justify-content: flex-start;
  align-items: center;
}

#auto-vehicle-plate-key-board
  .vehicle-plate-keyboard-container
  .keyboard
  .keyboard-container
  .keyboard-row
  .keyboard-cell {
  display: flex;
  justify-content: center;
  align-items: center;
}

#auto-vehicle-plate-key-board
  .vehicle-plate-keyboard-container
  .keyboard
  .keyboard-container
  .keyboard-row
  .keyboard-cell
  .cell-text {
  width: 100%;
  height: 100%;
  margin: 4px 2.5px;
  background-color: white;
  border-radius: 4px;
  display: flex;
  justify-content: center;
  align-items: center;
  font-size: 16px;
  color: #333;
}

#auto-vehicle-plate-key-board
  .vehicle-plate-keyboard-container
  .keyboard
  .keyboard-container
  .keyboard-row
  .cell-no-disabled:active {
    color: #333;
  /* background-color: #206cfe; */
}

#auto-vehicle-plate-key-board
  .vehicle-plate-keyboard-container
  .keyboard
  .keyboard-container
  .keyboard-row
  .cell-no-disabled:active
  .back-btn-svg {
  color: #fff;
  width: 100%;
  height: 100%;
  margin: 4px 2.5px;
  background-color: white;
  border-radius: 4px;
}

#auto-vehicle-plate-key-board
  .vehicle-plate-keyboard-container
  .keyboard
  .keyboard-container
  .keyboard-row
  .cell-no-disabled:active
  .cell-text {
  /* color: #333;
  opacity: 0.1; */
  background-color: #cfd1d5;
}

#auto-vehicle-plate-key-board
  .vehicle-plate-keyboard-container
  .keyboard
  .keyboard-container
  .keyboard-row
  .normal-cell {
  flex: 1;
  height: 44px;
  margin: 4px 0;
}

#auto-vehicle-plate-key-board
  .vehicle-plate-keyboard-container
  .keyboard
  .keyboard-container
  .keyboard-row
  .province-cell {
  flex:1;
  height: 44px;
  margin: 4px 2.5px;
}

#auto-vehicle-plate-key-board
  .vehicle-plate-keyboard-container
  .keyboard
  .keyboard-container
  .keyboard-row
  .number-cell {
  width: 120px;
  height: 44px;
  margin: 4px 2.5px;
}

#auto-vehicle-plate-key-board
  .vehicle-plate-keyboard-container
  .keyboard
  .keyboard-container
  .keyboard-row
  .character-cell {
  width: 54px;
  height: 44px;
  margin: 4px 2px;
}

#auto-vehicle-plate-key-board
  .vehicle-plate-keyboard-container
  .keyboard
  .keyboard-container
  .cell-disabled {
  opacity: 0.4;
}

#auto-vehicle-plate-key-board
  .vehicle-plate-keyboard-container
  .keyboard
  .keyboard-container
  .cell-disabled:active {
  background-color: white;
}

#auto-vehicle-plate-key-board
  .vehicle-plate-keyboard-container
  .keyboard
  .keyboard-container-number
  .keyboard-row
  .back-btn {
  flex: 2;
  height: 44px;
}

.back-btn-svg {
  width: 20px;
  height: 18px;
  line-height: 18px;
  padding-right: 6px;
  font-size: 20px;
  color: #213547;
}

.back-btn-label{
  font-size: 16px;
  color: #fff;
}


  </style>
